import React from 'react';

  
    const ProductBasededatos = [
   
    {
      id:1,
      "juego": "Zelda Skyward sword",
      "plataforma": "nintendo",
      "tipo_juego": "accion",
      "num_jugadores": "singleplayer",
      "accesorios": "NA",
      "precio": 389900,
      "restricción_edad": 12,
      "foto": "https://assets.nintendo.com/image/upload/c_fill,w_1200/q_auto:best/f_auto/dpr_2.0/ncom/software/switch/70010000038612/63595b0826bb6ece7b95e4eb2a33e5ad0559224b350a5e2974a44f772963ae59",
      "stock": 5
    },
    {id:2,
      "juego": "Mario kart 8",
      "plataforma": "nintendo",
      "tipo_juego": "carreras",
      "num_jugadores": "multiplayer",
      "accesorios": "na",
      "precio": 334900,
      "restricción_edad": 7,
      "foto": "https://images7.alphacoders.com/821/thumb-1920-821837.jpg",
      "stock": 10
    },
    { id:3,
      "juego": "animal crossing",
      "plataforma": "nintendo",
      "tipo_juego": "simulacion",
      "num_jugadores": "singleplayer",
      "accesorios": "NA",
      "precio": 235638,
      "restricción_edad": "na",
      "foto": "https://www.xtrafondos.com/descargar.php?id=6457&resolucion=3840x2160",
      "stock": 2
    },
    {id:4,
      "juego": "kirby and the forgotten land",
      "plataforma": "nintendo",
      "tipo_juego": "plataformeo",
      "num_jugadores": "singleplayer",
      "accesorios": "na",
      "precio": 249900,
      "restricción_edad": 10,
      "foto": "https://kirbyandtheforgottenland.nintendo.com/assets/images/share-fb.jpg",
      "stock": 1
    },
    {id:5,
      "juego": "Assassins Creed",
    "plataforma": "playstation",
    "tipo_juego": "accion",
    "num_jugadores": "singleplayer",
    "accesorios": "na",
    "precio": 354900,
    "restricción_edad": 13,
    "foto": "https://staticctf.ubisoft.com/J3yJr34U2pZ2Ieem48Dwy9uqj5PNUQTn/449BBgnc3Q1ha2IN9rh3bR/e1077125021162ce2d59820739c316e7/ACEC_Keyart_00_00_00_mobile.jpg",
    "stock": 5
    },
     { id:6,
      "juego": "Call of Duty",
    "plataforma": "playstation",
    "tipo_juego": "accion",
    "num_jugadores": "multiplayer",
    "accesorios": "na",
    "precio": 283900,
    "restricción_edad": 18,
    "foto": "https://c4.wallpaperflare.com/wallpaper/209/251/804/cod-mw-ghost-call-of-duty-hd-wallpaper-preview.jpg",
    "stock": 15
    },
     { id:7,
      "juego": "FIFA 2023",
    "plataforma": "playstation",
    "tipo_juego": "deportes",
    "num_jugadores": "multiplayer",
    "accesorios": "na",
    "precio": 329900,
    "restricción_edad": "na",
    "foto": "https://images5.alphacoders.com/128/1286044.jpg",
    "stock": 1
    },
    { id:8,
    "juego": "Ghost of Tsushima",
    "plataforma": "playstation",
    "tipo_juego": "accion",
    "num_jugadores": "singleplayer",
    "accesorios": "na",
    "precio": 249900,
    "restricción_edad": 17,
    "foto": "https://images5.alphacoders.com/105/thumb-1920-1056682.png",
    "stock": 20
    },
    { id:9,
    "juego": "Grand Theft Auto V",
    "plataforma": "playstation",
    "tipo_juego": "sandbox",
    "num_jugadores": "multiplayer",
    "accesorios": "na",
    "precio": 300000,
    "restricción_edad": 18,
    "foto": "https://fondosmil.com/fondo/57686.jpg",
    "stock": 20
    },
    { id:10,
    "juego": "Overwatch 2",
    "plataforma": "pc",
    "tipo_juego": "accion",
    "num_jugadores": "multiplayer",
    "accesorios": "na",
    "precio": 385900,
    "restricción_edad": 12,
    "foto": "https://images8.alphacoders.com/104/1049882.jpg",
    "stock": 20
    },
    { id:11,
    "juego": "fortnite",
    "plataforma": "pc",
    "tipo_juego": "accion",
    "num_jugadores": "multiplayer",
    "accesorios": "na",
    "precio": 251000,
    "restricción_edad": 10,
    "foto": "https://www.esportmaniacos.com/wp-content/uploads/2022/03/Fortnite-scaled1.jpg",
    "stock": 10
    },
    { id:12,
    "juego": "Gang Beasts",
    "plataforma": "pc",
    "tipo_juego": "supervivencia",
    "num_jugadores": "multiplayer",
    "accesorios": "na",
    "precio": 80000,
    "restricción_edad": "na",
    "foto": "https://gaminguardian.com/wp-content/uploads/2018/01/Gang-Beasts-portada.png",
    "stock": 30
    },
    { id:13,
    "juego": "God of War",
    "plataforma": "pc",
    "tipo_juego": "accion",
    "num_jugadores": "singleplayer",
    "accesorios": "na",
    "precio": 184000,
    "restricción_edad": 18,
    "foto": "https://images.alphacoders.com/173/173641.jpg",
    "stock": 15
    }

]

export default ProductBasededatos;